from __future__ import annotations

import re
from datetime import date
from decimal import Decimal
from hashlib import sha256
from pathlib import Path

from backend.app.ai.models import TrustedEvidence
from backend.app.intelligence.drilldown import FinancialDrilldownService


def _safe_evidence_id(prefix: str, raw: str) -> str:
    clean = re.sub(
        r"[^a-zA-Z0-9_.-]+",
        "_",
        str(raw).strip().lower(),
    ).strip("_")

    digest = sha256(
        str(raw).encode("utf-8")
    ).hexdigest()[:8]

    return f"{prefix}.{clean[:50]}.{digest}"


def _evidence(
    *,
    evidence_id: str,
    domain: str,
    metric: str,
    value: str,
    source_field: str,
    as_of_date: date,
) -> TrustedEvidence:
    return TrustedEvidence(
        evidence_id=evidence_id,
        domain=domain,
        metric=metric,
        value=(
            f"analysis_date={as_of_date.isoformat()}; "
            f"{str(value)}"
        )[:500],
        unit="text",
        source_field=source_field,
        as_of_date=as_of_date,
    )


def _mentioned(question: str, value: str) -> bool:
    value = str(value).strip()

    if not value:
        return False

    pattern = (
        r"(?<![A-Za-z0-9])"
        + re.escape(value)
        + r"(?![A-Za-z0-9])"
    )

    return bool(
        re.search(
            pattern,
            question,
            flags=re.IGNORECASE,
        )
    )


def _requested_limit(
    question: str,
    *,
    noun: str,
    total: int,
    default: int = 5,
) -> int:
    q = question.lower()

    if f"all {noun}" in q:
        return min(total, 30)

    match = re.search(
        r"\b(?:top|first)\s+(\d{1,2})\b",
        q,
    )

    if match:
        return min(
            max(1, int(match.group(1))),
            total,
            30,
        )

    match = re.search(
        rf"\b(\d{{1,2}})\s+(?:risky\s+)?{noun}\b",
        q,
    )

    if match:
        return min(
            max(1, int(match.group(1))),
            total,
            30,
        )

    return min(default, total)


def _chunk_rows(
    rows: list[str],
    size: int = 2,
) -> list[str]:
    return [
        " | ".join(rows[index:index + size])
        for index in range(
            0,
            len(rows),
            size,
        )
    ]


def build_question_evidence(
    *,
    question: str,
    raw_dir: str | Path,
    as_of_date: date,
    opening_cash_balance: Decimal,
    horizon_days: int,
) -> list[TrustedEvidence]:
    """
    Build question-specific deterministic evidence.

    Nothing here is generated by the LLM.
    The LLM only receives the resulting verified facts.
    """

    service = FinancialDrilldownService(
        raw_dir=raw_dir,
        as_of_date=as_of_date,
    )

    q = question.lower()

    invoices = service.invoice_intelligence()
    customers = service.customer_intelligence()

    evidence: list[TrustedEvidence] = []

    cash_terms = any(
        term in q
        for term in (
            "cashflow",
            "cash flow",
            "liquidity",
            "cash shortage",
            "shortfall",
            "cash gap",
            "affect cash",
            "impact cash",
        )
    )

    ranking_terms = any(
        term in q
        for term in (
            "top ",
            "highest",
            "riskiest",
            "risky",
            "largest",
            "biggest",
            "most",
            "major",
            "rank",
        )
    )

    customer_terms = any(
        term in q
        for term in (
            "customer",
            "customers",
            "client",
            "clients",
            "account",
        )
    )

    invoice_terms = any(
        term in q
        for term in (
            "invoice",
            "invoices",
            "receivable",
            "receivables",
        )
    )

    # -------------------------------------------------
    # 1. Detect explicit invoice IDs
    # -------------------------------------------------

    matched_invoices = [
        invoice
        for invoice in invoices
        if _mentioned(
            question,
            invoice["invoice_id"],
        )
    ]

    if matched_invoices:
        rows = []

        for invoice in matched_invoices:
            rows.append(
                (
                    f'{invoice["invoice_id"]}: '
                    f'customer={invoice["customer_id"]}, '
                    f'outstanding=INR '
                    f'{invoice["outstanding_amount"]}, '
                    f'late_probability='
                    f'{invoice["late_probability_pct"]}%, '
                    f'expected_delay='
                    f'{invoice["expected_delay_days"]} days, '
                    f'confidence='
                    f'{invoice["prediction_confidence_pct"]}%, '
                    f'risk={invoice["risk_level"]}'
                )
            )

        for index, chunk in enumerate(
            _chunk_rows(rows),
            start=1,
        ):
            evidence.append(
                _evidence(
                    evidence_id=(
                        f"invoice.lookup.{index}"
                    ),
                    domain="receivables",
                    metric="invoice drilldown",
                    value=chunk,
                    source_field=(
                        "drilldown.invoice_intelligence"
                    ),
                    as_of_date=as_of_date,
                )
            )

        return evidence

    # -------------------------------------------------
    # 2. Detect explicit customers by ID or full name
    # -------------------------------------------------

    matched_customers = []

    for customer in customers:
        customer_id = customer["customer_id"]
        customer_name = customer.get(
            "customer_name",
            "",
        )

        if (
            _mentioned(question, customer_id)
            or (
                customer_name
                and customer_name.lower() in q
            )
        ):
            matched_customers.append(customer)

    if matched_customers:
        for customer in matched_customers:
            customer_id = customer["customer_id"]

            summary = (
                f'{customer_id} '
                f'({customer.get("customer_name", "")}): '
                f'open_invoices='
                f'{customer["open_invoices"]}, '
                f'high_risk_invoices='
                f'{customer["high_risk_invoices"]}, '
                f'total_outstanding=INR '
                f'{customer["total_outstanding"]}, '
                f'predicted_delayed_exposure=INR '
                f'{customer["predicted_delayed_exposure"]}, '
                f'late_probability='
                f'{customer["weighted_late_probability_pct"]}%, '
                f'expected_delay='
                f'{customer["weighted_expected_delay_days"]} days, '
                f'risk={customer["risk_level"]}'
            )

            evidence.append(
                _evidence(
                    evidence_id=_safe_evidence_id(
                        "customer.summary",
                        customer_id,
                    ),
                    domain="receivables",
                    metric="customer drilldown",
                    value=summary,
                    source_field=(
                        "drilldown.customer_intelligence"
                    ),
                    as_of_date=as_of_date,
                )
            )

            if invoice_terms:
                related = [
                    invoice
                    for invoice in invoices
                    if invoice["customer_id"]
                    == customer_id
                ]

                rows = [
                    (
                        f'{invoice["invoice_id"]}: '
                        f'outstanding=INR '
                        f'{invoice["outstanding_amount"]}, '
                        f'risk='
                        f'{invoice["late_probability_pct"]}%, '
                        f'delay='
                        f'{invoice["expected_delay_days"]} days'
                    )
                    for invoice in related
                ]

                for index, chunk in enumerate(
                    _chunk_rows(rows),
                    start=1,
                ):
                    evidence.append(
                        _evidence(
                            evidence_id=(
                                _safe_evidence_id(
                                    "customer.invoices",
                                    (
                                        f"{customer_id}"
                                        f".{index}"
                                    ),
                                )
                            ),
                            domain="receivables",
                            metric=(
                                "customer invoice list"
                            ),
                            value=chunk,
                            source_field=(
                                "drilldown."
                                "invoice_intelligence"
                            ),
                            as_of_date=as_of_date,
                        )
                    )

            if cash_terms:
                impact = (
                    service.customer_cashflow_impact(
                        customer_id=customer_id,
                        opening_cash_balance=(
                            opening_cash_balance
                        ),
                        horizon_days=horizon_days,
                    )
                )

                impact_text = (
                    f'{customer_id}: '
                    f'delayed_exposure=INR '
                    f'{impact["predicted_delayed_exposure"]}, '
                    f'maximum_cash_gap=INR '
                    f'{impact["maximum_temporary_cash_gap"]}, '
                    f'gap_date={impact["maximum_gap_date"]}, '
                    f'reduced_liquidity='
                    f'{impact["days_with_reduced_liquidity"]} days, '
                    f'incremental_shortfall=INR '
                    f'{impact["incremental_shortfall"]}, '
                    f'severity={impact["severity"]}'
                )

                evidence.append(
                    _evidence(
                        evidence_id=_safe_evidence_id(
                            "customer.cashflow",
                            customer_id,
                        ),
                        domain="liquidity",
                        metric=(
                            "customer cashflow impact"
                        ),
                        value=impact_text,
                        source_field=(
                            "drilldown."
                            "customer_cashflow_impact"
                        ),
                        as_of_date=as_of_date,
                    )
                )

        return evidence

    # -------------------------------------------------
    # 3. Customer ranking / top-N analysis
    # -------------------------------------------------

    if customer_terms and (
        ranking_terms
        or cash_terms
        or "which customers" in q
        or "all customers" in q
    ):
        limit = _requested_limit(
            question,
            noun="customers",
            total=len(customers),
        )

        ranking = (
            service.rank_customers_by_cashflow_impact(
                opening_cash_balance=(
                    opening_cash_balance
                ),
                horizon_days=horizon_days,
                limit=limit,
            )
        )

        ranked = ranking["customers"]

        rows = [
            (
                f'#{customer["rank"]} '
                f'{customer["customer_id"]} '
                f'{customer["customer_name"]}: '
                f'outstanding=INR '
                f'{customer["total_outstanding"]}, '
                f'delayed_exposure=INR '
                f'{customer["predicted_delayed_exposure"]}, '
                f'max_cash_gap=INR '
                f'{customer["maximum_temporary_cash_gap"]}, '
                f'incremental_shortfall=INR '
                f'{customer["incremental_shortfall"]}, '
                f'liquidity_days='
                f'{customer["days_with_reduced_liquidity"]}, '
                f'severity={customer["severity"]}'
            )
            for customer in ranked
        ]

        for index, chunk in enumerate(
            _chunk_rows(rows),
            start=1,
        ):
            evidence.append(
                _evidence(
                    evidence_id=(
                        f"customer.ranking.{index}"
                    ),
                    domain="liquidity",
                    metric="customer cashflow ranking",
                    value=chunk,
                    source_field=(
                        "drilldown."
                        "rank_customers_by_cashflow_impact"
                    ),
                    as_of_date=as_of_date,
                )
            )

        evidence.append(
            _evidence(
                evidence_id="customer.ranking.basis",
                domain="liquidity",
                metric="customer ranking basis",
                value=(
                    f'Ranking basis='
                    f'{ranking["ranking_basis"]}; '
                    f'customers evaluated='
                    f'{ranking["customer_count_evaluated"]}; '
                    f'customers returned={len(ranked)}'
                ),
                source_field=(
                    "drilldown."
                    "rank_customers_by_cashflow_impact"
                ),
                as_of_date=as_of_date,
            )
        )

        # If the question asks how these top-N customers
        # affect cashflow, simulate them TOGETHER.
        if cash_terms and ranked:
            customer_ids = [
                customer["customer_id"]
                for customer in ranked
            ]

            combined = (
                service.combined_customer_cashflow_impact(
                    customer_ids=customer_ids,
                    opening_cash_balance=(
                        opening_cash_balance
                    ),
                    horizon_days=horizon_days,
                )
            )

            combined_text = (
                f'customers={len(customer_ids)}, '
                f'combined_outstanding=INR '
                f'{combined["combined_outstanding"]}, '
                f'combined_delayed_exposure=INR '
                f'{combined["combined_delayed_exposure"]}, '
                f'maximum_cash_gap=INR '
                f'{combined["maximum_temporary_cash_gap"]}, '
                f'maximum_gap_date='
                f'{combined["maximum_gap_date"]}, '
                f'reduced_liquidity='
                f'{combined["days_with_reduced_liquidity"]} days, '
                f'incremental_shortfall=INR '
                f'{combined["incremental_shortfall"]}, '
                f'severity={combined["severity"]}'
            )

            evidence.append(
                _evidence(
                    evidence_id=(
                        "customer.combined.cashflow"
                    ),
                    domain="liquidity",
                    metric=(
                        "combined customer cashflow impact"
                    ),
                    value=combined_text,
                    source_field=(
                        "drilldown."
                        "combined_customer_cashflow_impact"
                    ),
                    as_of_date=as_of_date,
                )
            )

        return evidence

    # -------------------------------------------------
    # 4. Top-N risky invoice / receivable questions
    # -------------------------------------------------

    if invoice_terms and (
        ranking_terms
        or "which receivables" in q
        or "highest risk" in q
    ):
        limit = _requested_limit(
            question,
            noun="invoices",
            total=len(invoices),
        )

        ranked = sorted(
            invoices,
            key=lambda invoice: (
                float(
                    invoice[
                        "late_probability_pct"
                    ]
                ),
                Decimal(
                    invoice[
                        "outstanding_amount"
                    ]
                ),
                int(
                    invoice[
                        "expected_delay_days"
                    ]
                ),
            ),
            reverse=True,
        )[:limit]

        rows = [
            (
                f'#{index} {invoice["invoice_id"]}: '
                f'customer={invoice["customer_id"]}, '
                f'outstanding=INR '
                f'{invoice["outstanding_amount"]}, '
                f'late_probability='
                f'{invoice["late_probability_pct"]}%, '
                f'expected_delay='
                f'{invoice["expected_delay_days"]} days, '
                f'confidence='
                f'{invoice["prediction_confidence_pct"]}%, '
                f'risk={invoice["risk_level"]}'
            )
            for index, invoice in enumerate(
                ranked,
                start=1,
            )
        ]

        for index, chunk in enumerate(
            _chunk_rows(rows),
            start=1,
        ):
            evidence.append(
                _evidence(
                    evidence_id=(
                        f"invoice.ranking.{index}"
                    ),
                    domain="receivables",
                    metric="invoice risk ranking",
                    value=chunk,
                    source_field=(
                        "drilldown.invoice_intelligence"
                    ),
                    as_of_date=as_of_date,
                )
            )

        return evidence

    return []
