from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Any


# ============================================================
# RECONCILIATION STATES
# ============================================================


class ReconciliationStatus(str, Enum):
    """
    Final state assigned to a finance case.
    """

    RECONCILED = "RECONCILED"

    EXPLAINED_EXCEPTION = "EXPLAINED_EXCEPTION"

    UNRESOLVED = "UNRESOLVED"

    HUMAN_REVIEW = "HUMAN_REVIEW"


# ============================================================
# MATCH METHODS
# ============================================================


class MatchMethod(str, Enum):
    """
    Describes how two financial records were connected.
    """

    EXACT_ID = "EXACT_ID"

    EXACT_REFERENCE = "EXACT_REFERENCE"

    EXACT_AMOUNT_DATE = "EXACT_AMOUNT_DATE"

    FUZZY = "FUZZY"

    NONE = "NONE"


# ============================================================
# ROOT-CAUSE TYPES
# ============================================================


class RootCause(str, Enum):
    """
    Known reconciliation outcomes.

    These are operational classifications generated by
    FlowGuard. They are NOT read from ground_truth.csv.
    """

    CLEAN = "CLEAN"

    GATEWAY_FEE_GST = "GATEWAY_FEE_GST"

    FULL_REFUND = "FULL_REFUND"

    PARTIAL_REFUND = "PARTIAL_REFUND"

    CHARGEBACK = "CHARGEBACK"

    PARTIAL_PAYMENT = "PARTIAL_PAYMENT"

    SETTLEMENT_DELAY = "SETTLEMENT_DELAY"

    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"

    MISSING_PAYMENT = "MISSING_PAYMENT"

    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"

    MISSING_BANK_ENTRY = "MISSING_BANK_ENTRY"

    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"

    FUZZY_REFERENCE = "FUZZY_REFERENCE"

    UNEXPLAINED = "UNEXPLAINED"


# ============================================================
# MATCH CANDIDATE
# ============================================================


@dataclass(slots=True)
class MatchCandidate:
    """
    One candidate record considered during matching.
    """

    record_id: str

    score: float

    method: MatchMethod

    evidence: dict[str, Any] = field(
        default_factory=dict
    )


# ============================================================
# MATCH DECISION
# ============================================================


@dataclass(slots=True)
class MatchDecision:
    """
    Final matching decision for one reconciliation stage.
    """

    matched: bool

    record_id: str | None

    confidence: float

    method: MatchMethod

    requires_review: bool = False

    evidence: dict[str, Any] = field(
        default_factory=dict
    )


# ============================================================
# ROOT-CAUSE DECISION
# ============================================================


@dataclass(slots=True)
class RootCauseDecision:
    """
    Result produced by the root-cause investigation layer.
    """

    root_cause: RootCause

    status: ReconciliationStatus

    confidence: float

    explanation: str

    recommended_action: str

    requires_review: bool

    evidence: dict[str, Any] = field(
        default_factory=dict
    )


# ============================================================
# FINAL RECONCILIATION RESULT
# ============================================================


@dataclass(slots=True)
class ReconciliationResult:
    """
    Complete FlowGuard output for one invoice.

    This is intentionally independent from benchmark labels.
    """

    invoice_id: str

    customer_id: str

    customer_name: str

    invoice_amount: Decimal

    payment_ids: list[str] = field(
        default_factory=list
    )

    settlement_ids: list[str] = field(
        default_factory=list
    )

    bank_transaction_ids: list[str] = field(
        default_factory=list
    )

    payment_amount: Decimal = Decimal("0.00")

    expected_settlement: Decimal = Decimal("0.00")

    actual_bank_amount: Decimal = Decimal("0.00")

    difference: Decimal = Decimal("0.00")

    status: ReconciliationStatus = (
        ReconciliationStatus.UNRESOLVED
    )

    root_cause: RootCause = RootCause.UNEXPLAINED

    confidence: float = 0.0

    match_method: MatchMethod = MatchMethod.NONE

    requires_review: bool = True

    explanation: str = ""

    recommended_action: str = ""

    evidence: dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(self) -> dict[str, Any]:
        """
        Convert result into a serializable dictionary.

        Decimal values are kept as strings to avoid
        floating-point precision errors in financial output.
        """

        return {
            "invoice_id": self.invoice_id,
            "customer_id": self.customer_id,
            "customer_name": self.customer_name,

            "invoice_amount": str(
                self.invoice_amount
            ),

            "payment_ids": self.payment_ids,

            "settlement_ids": self.settlement_ids,

            "bank_transaction_ids":
                self.bank_transaction_ids,

            "payment_amount": str(
                self.payment_amount
            ),

            "expected_settlement": str(
                self.expected_settlement
            ),

            "actual_bank_amount": str(
                self.actual_bank_amount
            ),

            "difference": str(
                self.difference
            ),

            "status": self.status.value,

            "root_cause": self.root_cause.value,

            "confidence": round(
                self.confidence,
                2
            ),

            "match_method":
                self.match_method.value,

            "requires_review":
                self.requires_review,

            "explanation":
                self.explanation,

            "recommended_action":
                self.recommended_action,

            "evidence":
                self.evidence,
        }